### ISSUE TITLE
/POST /restId/reviews

### ISSUE THREAD

**Issue by bmj1988** [bmj1988/byte-bite#10]
- [x] An authenticated user is required for a successful response
- [x] New review exists in the database after request
- [x] Review data returned includes the `id`, `review`, `stars`, `userId`, `restaurantId`, `createdAt`, and `updatedAt`
- [x] Error response with status 400 is given when body validations for the
  `review` or `stars` are violated
- [x] Error response with status 404 is given when a spot does not exist with
  the provided `id`
- [x] Error response with status 403 is given when a review already exists for
  the spot from the current user

**Comment by gerrodww** [comment]
Backend route created at /api/reviews/restaurant_id

sending a post request to this route will create a review associated with that restaurant and logged in user sending request

error handling: must be logged in, must have submitted a review, must not be owner of restaurant, restaurant must exist
