### ISSUE TITLE
Edit a Review

### ISSUE THREAD

**Issue by bmj1988** [bmj1988/byte-bite#11]
/PUT /restId/reviews/reviewId
- [x] An authenticated user is required for a successful response
- [x] Only the owner of the review is authorized to edit
- [x] Review record is updated in the database after request
- [x] Review data returned includes the `id`, `review`, `stars`, `userId`, `restaurantId`, `createdAt`, and `updatedAt`
- [x] Error response with status 400 is given when body validations for the
  `review`, or `stars` are violated
- [x] Error response with status 404 is given when a review does not exist with
  the provided `id`

**Comment by gerrodww** [comment]
Backend route created at /api/reviews/estaurant_id

sending a put request to this route will edit the review associated with that restaurant and logged in user sending request

error handling: must be logged in, must have submitted a review, must not be owner of restaurant, restaurant must exist
