### ISSUE TITLE
Delete a Review

### ISSUE THREAD

**Issue by bmj1988** [bmj1988/byte-bite#12]
/DELETE /restId/reviews/reviewId
- [x] An authenticated user is required for a successful response
- [x] Only the owner of the review is authorized to delete
- [x] Review record is removed from the database after request
- [x] Success response includes a `message` indicating a successful deletion
- [x] Error response with status 404 is given when a spot does not exist with
  the provided `id`

**Comment by gerrodww** [comment]
Backend route created at /api/reviews/restaurant_id

sending a delete request to this route will delete the review associated with that restaurant and logged in user sending request

error handling: must be logged in, must have submitted a review, must not be owner of restaurant, restaurant must exist
