### ISSUE TITLE
/GET restaurant by RestaurantId

### ISSUE THREAD

**Issue by bmj1988** [bmj1988/byte-bite#17]
- [x] Seed data exists in the database for menuItems to be returned.
 - [x] Successful response includes only menuItems for the specified restaurantId
 - [x] Review data returned includes the id, name, price, image, description, and restaurantId

**Comment by AnthonyBronca** [comment]
@bmj1988 Please close this issue if complete

**Comment by bmj1988** [comment]
Get Restaurant by ID Api route is the main route for a storepage, this allows us to retrieve all the details of a restaurant to display
