### ISSUE TITLE
Update DB schema

### ISSUE THREAD

**Issue by bmj1988** [bmj1988/byte-bite#29]
Open list of all the DB Schema issues that need resolution, update as new issues surface.

- [x] restaurants attr "delivers" should be changed to "delivery"
- [x] driver should be converted from a foreign key using user id to a randomly generated name when someone creates an order, using Faker
- [x] take a pass over the DB schema to use python naming convention instead of camel case
- [x] consider removing the "phone" attribute from restaurants, can't see how it would come up during during the project.
- [x] Consider removing "country" attribute from restaurants.

**Comment by AnthonyBronca** [comment]
Hey @bmj1988 , what's the status on this issue? Can this be closed? If so, make sure to click the project this is related to and include any additional labels as needed. You may also want to close with a comment of things you did to solve/not solve this

**Comment by bmj1988** [comment]
DB schema has been finalized barring any changes to the structure of the project.
