### ISSUE TITLE
/GET /:restaurantName/menuItems/:menuItemId

### ISSUE THREAD

**Issue by Dlegendre1** [bmj1988/byte-bite#40]
- [x] Return API Doc data

**Comment by AnthonyBronca** [comment]
Hey @Dlegendre1 , what's the status on this issue? Can this be closed? If so, make sure to click the project this is related to and include any additional labels as needed. You may also want to close with a comment of things you did to solve/not solve this

**Comment by bmj1988** [comment]
Likely will not have to Read the menu items in this fashion (they should all be returned via association with a Restaurant) but this route allows for quick testing of newly created/deleted menu items
