### ISSUE TITLE
/POST /:restaurantName/menuItems/:menuItemId

### ISSUE THREAD

**Issue by Dlegendre1** [bmj1988/byte-bite#41]
- [x] Return API Doc information

**Comment by AnthonyBronca** [comment]
Hey @Dlegendre1 , what's the status on this issue? Can this be closed? If so, make sure to click the project this is related to and include any additional labels as needed. You may also want to close with a comment of things you did to solve/not solve this

**Comment by bmj1988** [comment]
The post route for menu items is written and allows the owner of a restaurant to add menu items to the restaurant.
